# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Richard.H's Note ｜ R-笔记本
email:       'frhong+note+rh@gmail.com'
description: 'This is a personal note'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://note.richardhong.com' # The base hostname & protocol for your site
twitter:     '@frhong'
# github:      ''
# instagram:   ''
# facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  5
encoding: UTF-8

sass:
  style: compressed

destination: docs

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
